import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.shelly.getAll.useQuery()
  const { mutate } = api.shelly.postToggleDevice.useMutation({ onSuccess: (data) => console.log(data) })
  console.log(data);


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Shelly <span className="text-[hsl(280,100%,70%)]">Relay</span> Control
          </h1>

          {
            data && data.devices.length ? (
              <ul className="tracking-tight text-white sm:text-[5rem]">
                {data.devices.map((device) => (
                  <li className="text-2xl font-extrabold flex flex-col">
                    {device.name}
                    <div className="grid grid-cols-2 gap-3">

                      <button className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2" onClick={() => mutate({ deviceId: device.id, turn: "on", channel: 0 })}>Channel 1 On</button>
                      <button className="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2" onClick={() => mutate({ deviceId: device.id, turn: "off", channel: 0 })}>Channel 1 Off</button>
                      <button className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2" onClick={() => mutate({ deviceId: device.id, turn: "on", channel: 1 })}>Channel 2 On</button>
                      <button className="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2" onClick={() => mutate({ deviceId: device.id, turn: "off", channel: 1 })}>Channel 2 Off</button>
                    </div>
                  </li>
                ))}
              </ul>) : null
          }

        </div>
      </main>
    </>
  );
}
